/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.RegionController;
import entities.Region;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.MyConnection;

/**
 *
 * @author MUHAMMAD BIN ZANDRA
 */
public class RegionView extends javax.swing.JInternalFrame {
    
    private RegionController regionController;
    private final String[] header = {"Region ID", "Region Name"};
    private final String[] categories;
    
    /**
     * Creates new form RegionView
     */
    public RegionView() {
        this.categories = new String[]{"region_id", "region_name"};
        initComponents();
        this.regionController = new RegionController(new MyConnection().getConnection());
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRegion = new javax.swing.JTable();
        panelRegion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idtextfieldRegion = new javax.swing.JTextField();
        nametxtfieldegion = new javax.swing.JTextField();
        savebtnRegion = new javax.swing.JButton();
        dropbtnregion = new javax.swing.JButton();
        findcomboRegion = new javax.swing.JComboBox<>();
        findtxtfieldRegion = new javax.swing.JTextField();
        findbtnRegion = new javax.swing.JButton();

        setTitle("Region");

        tabelRegion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRegionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRegion);

        panelRegion.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        panelRegion.setName(""); // NOI18N

        jLabel1.setText("Region ID");

        jLabel2.setText("Region Name");

        savebtnRegion.setText("Save");
        savebtnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnRegionActionPerformed(evt);
            }
        });

        dropbtnregion.setText("Drop");
        dropbtnregion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropbtnregionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegionLayout = new javax.swing.GroupLayout(panelRegion);
        panelRegion.setLayout(panelRegionLayout);
        panelRegionLayout.setHorizontalGroup(
            panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegionLayout.createSequentialGroup()
                        .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtextfieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxtfieldegion, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegionLayout.createSequentialGroup()
                        .addComponent(dropbtnregion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(savebtnRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelRegionLayout.setVerticalGroup(
            panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idtextfieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametxtfieldegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtnRegion)
                    .addComponent(dropbtnregion))
                .addGap(136, 136, 136))
        );

        findcomboRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));

        findbtnRegion.setText("Find");
        findbtnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRegion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(findcomboRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findtxtfieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findbtnRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findcomboRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findtxtfieldRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findbtnRegion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnRegionActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        if (idtextfieldRegion.isEnabled()) {
            flag = this.regionController.save(Integer.parseInt(idtextfieldRegion.getText()),
                    nametxtfieldegion.getText());
        } else {
            flag = this.regionController.edit(Integer.parseInt(idtextfieldRegion.getText()),
                    nametxtfieldegion.getText());
        }
        String ms = "failed";
        if (flag) {
            ms = "Success";
        }
        JOptionPane.showMessageDialog(this, ms, title, WIDTH);
//        bindingTable();
        reset();

    }//GEN-LAST:event_savebtnRegionActionPerformed

    private void findbtnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnRegionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_findbtnRegionActionPerformed

    private void tabelRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRegionMouseClicked
        // TODO add your handling code here:
        
        
        int row = tabelRegion.getSelectedRow();
                idtextfieldRegion.setText(tabelRegion.getValueAt(row, 0).toString());
        nametxtfieldegion.setText(tabelRegion.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tabelRegionMouseClicked

    private void dropbtnregionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropbtnregionActionPerformed
        // TODO add your handling code here:
        String msg = "failed drop";
        int flag = JOptionPane.showConfirmDialog(this, "really");
        if (flag == 0) {

            if (regionController.drop(Integer.parseInt(idtextfieldRegion.getText()))) {
                msg = "success drop";
            }
            JOptionPane.showMessageDialog(this, msg);
        }
//        bindingTable();
        reset();
    }//GEN-LAST:event_dropbtnregionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dropbtnregion;
    private javax.swing.JButton findbtnRegion;
    private javax.swing.JComboBox<String> findcomboRegion;
    private javax.swing.JTextField findtxtfieldRegion;
    private javax.swing.JTextField idtextfieldRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField nametxtfieldegion;
    private javax.swing.JPanel panelRegion;
    private javax.swing.JButton savebtnRegion;
    private javax.swing.JTable tabelRegion;
    // End of variables declaration//GEN-END:variables

    
//    public void bindingTable(){
//    String[] header = {"Id","Name"};
//    
//    DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
//    
//        for (Region region : regionController.binding()) {
//            
//            Object[] region1 = {
//                region.getRegionId(), region.getRegionName()
//            };
//            defaultTableModel.addRow(region1);
//        }
//        tabelRegion.setModel(defaultTableModel);
//        
//    }
    
//    public void searchTable(){
//    String[] header = {"ID","Name"};
//    
//    DefaultTableModel defaultTableModel = new DefaultTableModel(header, 0);
//    
//        for (Region region : regionController.find(findcomboRegion.getSelectedItem().toString(), findtxtfieldRegion.getText())) {
//            
//            Object[] region1 = {
//                region.getRegionId(), region.getRegionName()
//            };
//            defaultTableModel.addRow(region1);
//        }
//        tabelRegion.setModel(defaultTableModel);
//        
//    }
    
    public void reset (){
     idtextfieldRegion.setText("");
     nametxtfieldegion.setText("");
    
    }

}
